"""upstash-box — Python SDK for Upstash Box.

Exposes the synchronous client (``Box`` / ``EphemeralBox`` / ``Run`` /
``StreamRun``) as canonical names, plus the async variants (``AsyncBox`` etc.).
"""

from __future__ import annotations

from ._async import AsyncBox, AsyncEphemeralBox, AsyncRun, AsyncStreamRun
from ._common import infer_default_provider
from ._sync import Box, EphemeralBox, Run, StreamRun
from .custom_harness import (
    CustomHarnessContext,
    CustomHarnessDone,
    CustomHarnessEmitter,
    run_custom_harness,
)
from .errors import BoxError
from .types import (
    Agent,
    AgentScheduleOptions,
    Base64FileInput,
    BoxApiKey,
    BoxData,
    BoxRunData,
    BoxSize,
    Chunk,
    ClaudeCode,
    CodeLanguage,
    CursorModel,
    CustomHarnessConfig,
    EphemeralBoxData,
    ExecExitChunk,
    ExecOutputChunk,
    ExecScheduleOptions,
    ExecStreamChunk,
    FileEntry,
    FinishChunk,
    FinishUsage,
    GitCommitResult,
    GitConfigResult,
    LogEntry,
    McpServerConfig,
    NetworkPolicy,
    OpenAICodex,
    OpenCodeModel,
    OpenRouterModel,
    PromptFiles,
    PublicURL,
    PullRequest,
    ReasoningChunk,
    RunCost,
    RunLog,
    RunOptions,
    RunStatus,
    Runtime,
    Schedule,
    ScheduleStatus,
    Snapshot,
    StartChunk,
    StatsChunk,
    StreamOptions,
    TextDeltaChunk,
    ToolCallChunk,
    ToolResultChunk,
    UnknownChunk,
    VercelModel,
    WebhookConfig,
)

__version__ = "0.1.0"

__all__ = [
    # Clients (sync canonical + async variants)
    "Box",
    "EphemeralBox",
    "Run",
    "StreamRun",
    "AsyncBox",
    "AsyncEphemeralBox",
    "AsyncRun",
    "AsyncStreamRun",
    # Errors / helpers
    "BoxError",
    "infer_default_provider",
    "run_custom_harness",
    "CustomHarnessContext",
    "CustomHarnessDone",
    "CustomHarnessEmitter",
    # Enums
    "Agent",
    "BoxApiKey",
    "ClaudeCode",
    "CursorModel",
    "OpenAICodex",
    "OpenCodeModel",
    "OpenRouterModel",
    "VercelModel",
    # Config / option types
    "AgentScheduleOptions",
    "Base64FileInput",
    "CodeLanguage",
    "CustomHarnessConfig",
    "ExecScheduleOptions",
    "McpServerConfig",
    "NetworkPolicy",
    "PromptFiles",
    "RunOptions",
    "StreamOptions",
    "WebhookConfig",
    "Runtime",
    "BoxSize",
    "RunStatus",
    "ScheduleStatus",
    # Response models / chunks
    "BoxData",
    "BoxRunData",
    "EphemeralBoxData",
    "FileEntry",
    "GitCommitResult",
    "GitConfigResult",
    "LogEntry",
    "PublicURL",
    "PullRequest",
    "RunCost",
    "RunLog",
    "Schedule",
    "Snapshot",
    "Chunk",
    "StartChunk",
    "TextDeltaChunk",
    "ReasoningChunk",
    "ToolCallChunk",
    "ToolResultChunk",
    "FinishChunk",
    "FinishUsage",
    "StatsChunk",
    "UnknownChunk",
    "ExecStreamChunk",
    "ExecOutputChunk",
    "ExecExitChunk",
]
