"""upstash-box — Python SDK for Upstash Box.

Exposes the synchronous client (``Box`` / ``EphemeralBox`` / ``Run`` /
``StreamRun``) as canonical names, plus the async variants (``AsyncBox`` etc.).
"""

from __future__ import annotations

from ._async import (
    AsyncAgentNamespace,
    AsyncBox,
    AsyncEphemeralBox,
    AsyncExecNamespace,
    AsyncFilesNamespace,
    AsyncGitNamespace,
    AsyncRun,
    AsyncScheduleNamespace,
    AsyncSkillsNamespace,
    AsyncStreamRun,
)
from ._common import infer_default_provider
from ._sync import (
    AgentNamespace,
    Box,
    EphemeralBox,
    ExecNamespace,
    FilesNamespace,
    GitNamespace,
    Run,
    ScheduleNamespace,
    SkillsNamespace,
    StreamRun,
)
from ._version import __version__
from .custom_harness import (
    CustomHarnessContext,
    CustomHarnessDone,
    CustomHarnessEmitter,
    run_custom_harness,
)
from .errors import BoxError
from .types import (
    Agent,
    AgentConfig,
    AgentOptions,
    AgentScheduleOptions,
    Base64FileInput,
    BoxApiKey,
    BoxConfig,
    BoxConnectionOptions,
    BoxData,
    BoxGetOptions,
    BoxRunData,
    BoxSize,
    Chunk,
    ClaudeCode,
    ClaudeCodeAgentOptions,
    CodeLanguage,
    CodexAgentOptions,
    CursorAgentOptions,
    CursorModel,
    CustomHarnessConfig,
    EphemeralBoxConfig,
    EphemeralBoxData,
    ExecExitChunk,
    ExecOutputChunk,
    ExecScheduleOptions,
    ExecStreamChunk,
    FileEntry,
    FinishChunk,
    FinishUsage,
    GitCommitResult,
    GitConfigInput,
    GitConfigResult,
    ListOptions,
    LogEntry,
    McpServerConfig,
    ModelConfig,
    NetworkPolicy,
    OpenAICodex,
    OpenCodeAgentOptions,
    OpenCodeModel,
    OpenRouterModel,
    PromptFiles,
    PublicURL,
    PullRequest,
    ReasoningChunk,
    RunCost,
    RunLog,
    RunOptions,
    RunStatus,
    Runtime,
    Schedule,
    ScheduleStatus,
    Snapshot,
    StartChunk,
    StatsChunk,
    StreamOptions,
    TextDeltaChunk,
    ToolCallChunk,
    ToolResultCallback,
    ToolResultChunk,
    ToolResultPayload,
    ToolUseCallback,
    ToolUsePayload,
    UnknownChunk,
    UploadFileEntry,
    VercelModel,
    WebhookConfig,
)

__all__ = [
    "__version__",
    # Clients (sync canonical + async variants)
    "Box",
    "EphemeralBox",
    "Run",
    "StreamRun",
    "AsyncBox",
    "AsyncEphemeralBox",
    "AsyncRun",
    "AsyncStreamRun",
    # Namespace classes (the types of box.agent / box.exec / etc.)
    "AgentNamespace",
    "ExecNamespace",
    "FilesNamespace",
    "GitNamespace",
    "ScheduleNamespace",
    "SkillsNamespace",
    "AsyncAgentNamespace",
    "AsyncExecNamespace",
    "AsyncFilesNamespace",
    "AsyncGitNamespace",
    "AsyncScheduleNamespace",
    "AsyncSkillsNamespace",
    # Errors / helpers
    "BoxError",
    "infer_default_provider",
    "run_custom_harness",
    "CustomHarnessContext",
    "CustomHarnessDone",
    "CustomHarnessEmitter",
    # Enums
    "Agent",
    "BoxApiKey",
    "ClaudeCode",
    "CursorModel",
    "OpenAICodex",
    "OpenCodeModel",
    "OpenRouterModel",
    "VercelModel",
    # Config / option types
    "AgentConfig",
    "AgentOptions",
    "AgentScheduleOptions",
    "BoxConfig",
    "BoxConnectionOptions",
    "BoxGetOptions",
    "ListOptions",
    "EphemeralBoxConfig",
    "ModelConfig",
    "UploadFileEntry",
    "Base64FileInput",
    "ClaudeCodeAgentOptions",
    "CodexAgentOptions",
    "OpenCodeAgentOptions",
    "CursorAgentOptions",
    "ToolUseCallback",
    "ToolResultCallback",
    "ToolUsePayload",
    "ToolResultPayload",
    "CodeLanguage",
    "CustomHarnessConfig",
    "ExecScheduleOptions",
    "GitConfigInput",
    "McpServerConfig",
    "NetworkPolicy",
    "PromptFiles",
    "RunOptions",
    "StreamOptions",
    "WebhookConfig",
    "Runtime",
    "BoxSize",
    "RunStatus",
    "ScheduleStatus",
    # Response models / chunks
    "BoxData",
    "BoxRunData",
    "EphemeralBoxData",
    "FileEntry",
    "GitCommitResult",
    "GitConfigResult",
    "LogEntry",
    "PublicURL",
    "PullRequest",
    "RunCost",
    "RunLog",
    "Schedule",
    "Snapshot",
    "Chunk",
    "StartChunk",
    "TextDeltaChunk",
    "ReasoningChunk",
    "ToolCallChunk",
    "ToolResultChunk",
    "FinishChunk",
    "FinishUsage",
    "StatsChunk",
    "UnknownChunk",
    "ExecStreamChunk",
    "ExecOutputChunk",
    "ExecExitChunk",
]
