import {
  Agent,
  ClaudeCode,
  CursorModel,
  OpenAICodex,
  OpenCodeModel,
  OpenRouterModel,
  VercelModel,
} from "@upstash/box";

/** Model options grouped by agent */
export const MODEL_OPTIONS_BY_AGENT: Record<
  Agent,
  { label: string; options: { value: string; label: string }[] }[]
> = {
  [Agent.ClaudeCode]: [
    {
      label: "Anthropic",
      options: [
        { value: ClaudeCode.Opus_4_8, label: "Claude Opus 4.8" },
        { value: ClaudeCode.Opus_4_7, label: "Claude Opus 4.7" },
        { value: ClaudeCode.Opus_4_6, label: "Claude Opus 4.6" },
        { value: ClaudeCode.Opus_4_5, label: "Claude Opus 4.5" },
        { value: ClaudeCode.Sonnet_4_6, label: "Claude Sonnet 4.6" },
        { value: ClaudeCode.Sonnet_4_5, label: "Claude Sonnet 4.5" },
        { value: ClaudeCode.Sonnet_4, label: "Claude Sonnet 4" },
        { value: ClaudeCode.Haiku_4_5, label: "Claude Haiku 4.5" },
      ],
    },
    {
      label: "OpenRouter",
      options: [
        { value: OpenRouterModel.Claude_Opus_4_5, label: "Claude Opus 4.5 (OR)" },
        { value: OpenRouterModel.Claude_Sonnet_4, label: "Claude Sonnet 4 (OR)" },
        { value: OpenRouterModel.Claude_Haiku_4_5, label: "Claude Haiku 4.5 (OR)" },
        { value: OpenRouterModel.DeepSeek_R1, label: "DeepSeek R1 (OR)" },
        { value: OpenRouterModel.Gemini_2_5_Pro, label: "Gemini 2.5 Pro (OR)" },
        { value: OpenRouterModel.Gemini_2_5_Flash, label: "Gemini 2.5 Flash (OR)" },
        { value: OpenRouterModel.GPT_4_1, label: "GPT-4.1 (OR)" },
        { value: OpenRouterModel.O3, label: "o3 (OR)" },
        { value: OpenRouterModel.O4_Mini, label: "o4-mini (OR)" },
      ],
    },
    {
      label: "Vercel AI Gateway",
      options: [
        { value: VercelModel.Claude_Opus_4_7, label: "Claude Opus 4.7 (Vercel)" },
        { value: VercelModel.Claude_Sonnet_4_6, label: "Claude Sonnet 4.6 (Vercel)" },
        { value: VercelModel.Claude_Opus_4_6, label: "Claude Opus 4.6 (Vercel)" },
        { value: VercelModel.Claude_Haiku_4_5, label: "Claude Haiku 4.5 (Vercel)" },
        { value: VercelModel.Gemini_3_5_Flash, label: "Gemini 3.5 Flash (Vercel)" },
        { value: VercelModel.Grok_Build_0_1, label: "Grok Build 0.1 (Vercel)" },
        { value: VercelModel.Grok_4_3, label: "Grok 4.3 (Vercel)" },
      ],
    },
  ],
  [Agent.Codex]: [
    {
      label: "OpenAI",
      options: [
        { value: OpenAICodex.GPT_5_5, label: "GPT-5.5" },
        { value: OpenAICodex.GPT_5_4, label: "GPT-5.4" },
        { value: OpenAICodex.GPT_5_4_Mini, label: "GPT-5.4 Mini" },
        { value: OpenAICodex.GPT_5_3_Codex, label: "GPT-5.3 Codex" },
        { value: OpenAICodex.GPT_5_3_Codex_Spark, label: "GPT-5.3 Codex Spark" },
        { value: OpenAICodex.GPT_5_2_Codex, label: "GPT-5.2 Codex" },
        { value: OpenAICodex.GPT_5_1_Codex_Max, label: "GPT-5.1 Codex Max" },
        { value: OpenAICodex.GPT_5_1_Codex_Mini, label: "GPT-5.1 Codex Mini" },
      ],
    },
    {
      label: "OpenRouter",
      options: [
        { value: OpenRouterModel.Claude_Opus_4_5, label: "Claude Opus 4.5 (OR)" },
        { value: OpenRouterModel.Claude_Sonnet_4, label: "Claude Sonnet 4 (OR)" },
        { value: OpenRouterModel.Claude_Haiku_4_5, label: "Claude Haiku 4.5 (OR)" },
        { value: OpenRouterModel.DeepSeek_R1, label: "DeepSeek R1 (OR)" },
        { value: OpenRouterModel.Gemini_2_5_Pro, label: "Gemini 2.5 Pro (OR)" },
        { value: OpenRouterModel.Gemini_2_5_Flash, label: "Gemini 2.5 Flash (OR)" },
        { value: OpenRouterModel.GPT_4_1, label: "GPT-4.1 (OR)" },
        { value: OpenRouterModel.O3, label: "o3 (OR)" },
        { value: OpenRouterModel.O4_Mini, label: "o4-mini (OR)" },
      ],
    },
    {
      label: "Vercel AI Gateway",
      options: [
        { value: VercelModel.GPT_5_5, label: "GPT-5.5 (Vercel)" },
        { value: VercelModel.GPT_5_5_Pro, label: "GPT-5.5 Pro (Vercel)" },
        { value: VercelModel.GPT_5_4, label: "GPT-5.4 (Vercel)" },
        { value: VercelModel.GPT_5_4_Mini, label: "GPT-5.4 Mini (Vercel)" },
        { value: VercelModel.Claude_Opus_4_7, label: "Claude Opus 4.7 (Vercel)" },
        { value: VercelModel.Claude_Sonnet_4_6, label: "Claude Sonnet 4.6 (Vercel)" },
      ],
    },
  ],
  [Agent.OpenCode]: [
    {
      label: "OpenCode — Free",
      options: [
        { value: OpenCodeModel.Zen_GPT_5_Nano, label: "GPT-5 Nano (Free)" },
        { value: OpenCodeModel.Zen_Big_Pickle, label: "Big Pickle (Free)" },
      ],
    },
    {
      label: "OpenCode — Paid",
      options: [
        { value: OpenCodeModel.Zen_MiniMax_M2_7, label: "MiniMax M2.7" },
        { value: OpenCodeModel.Zen_Claude_Sonnet_4_6, label: "Claude Sonnet 4.6" },
        { value: OpenCodeModel.Zen_Claude_Sonnet_4_5, label: "Claude Sonnet 4.5" },
        { value: OpenCodeModel.Zen_Claude_Sonnet_4, label: "Claude Sonnet 4" },
        { value: OpenCodeModel.Zen_Claude_Haiku_4_5, label: "Claude Haiku 4.5" },
        { value: OpenCodeModel.Zen_Claude_Opus_4_8, label: "Claude Opus 4.8" },
        { value: OpenCodeModel.Zen_Claude_Opus_4_7, label: "Claude Opus 4.7" },
        { value: OpenCodeModel.Zen_Claude_Opus_4_6, label: "Claude Opus 4.6" },
        { value: OpenCodeModel.Zen_Claude_Opus_4_5, label: "Claude Opus 4.5" },
        { value: OpenCodeModel.Zen_Claude_Opus_4_1, label: "Claude Opus 4.1" },
        { value: OpenCodeModel.Zen_Gemini_3_1_Pro, label: "Gemini 3.1 Pro" },
        { value: OpenCodeModel.Zen_Gemini_3_Pro, label: "Gemini 3 Pro" },
        { value: OpenCodeModel.Zen_Gemini_3_Flash, label: "Gemini 3 Flash" },
      ],
    },
    {
      label: "Anthropic",
      options: [
        { value: OpenCodeModel.Claude_Opus_4_8, label: "Claude Opus 4.8" },
        { value: OpenCodeModel.Claude_Opus_4_7, label: "Claude Opus 4.7" },
        { value: OpenCodeModel.Claude_Opus_4_6, label: "Claude Opus 4.6" },
        { value: OpenCodeModel.Claude_Opus_4_5, label: "Claude Opus 4.5" },
        { value: OpenCodeModel.Claude_Sonnet_4_6, label: "Claude Sonnet 4.6" },
        { value: OpenCodeModel.Claude_Sonnet_4_5, label: "Claude Sonnet 4.5" },
        { value: OpenCodeModel.Claude_Sonnet_4, label: "Claude Sonnet 4" },
        { value: OpenCodeModel.Claude_Haiku_4_5, label: "Claude Haiku 4.5" },
      ],
    },
    {
      label: "OpenAI",
      options: [
        { value: OpenCodeModel.GPT_5_5, label: "GPT-5.5" },
        { value: OpenCodeModel.GPT_5_4_Pro, label: "GPT-5.4 Pro" },
        { value: OpenCodeModel.GPT_5_4, label: "GPT-5.4" },
        { value: OpenCodeModel.GPT_5_4_Mini, label: "GPT-5.4 Mini" },
        { value: OpenCodeModel.GPT_5_4_Nano, label: "GPT-5.4 Nano" },
        { value: OpenCodeModel.GPT_5_3_Codex, label: "GPT-5.3 Codex" },
        { value: OpenCodeModel.GPT_5_3_Codex_Spark, label: "GPT-5.3 Codex Spark" },
        { value: OpenCodeModel.GPT_5_2_Codex, label: "GPT-5.2 Codex" },
        { value: OpenCodeModel.GPT_5_1_Codex_Max, label: "GPT-5.1 Codex Max" },
        { value: OpenCodeModel.GPT_5_1_Codex_Mini, label: "GPT-5.1 Codex Mini" },
        { value: OpenCodeModel.GPT_4_1, label: "GPT-4.1" },
        { value: OpenCodeModel.O3, label: "o3" },
        { value: OpenCodeModel.O4_Mini, label: "o4-mini" },
      ],
    },
    {
      label: "OpenRouter",
      options: [
        { value: OpenRouterModel.Claude_Opus_4_5, label: "Claude Opus 4.5 (OR)" },
        { value: OpenRouterModel.Claude_Sonnet_4, label: "Claude Sonnet 4 (OR)" },
        { value: OpenRouterModel.Claude_Haiku_4_5, label: "Claude Haiku 4.5 (OR)" },
        { value: OpenRouterModel.DeepSeek_R1, label: "DeepSeek R1 (OR)" },
        { value: OpenRouterModel.Gemini_2_5_Pro, label: "Gemini 2.5 Pro (OR)" },
        { value: OpenRouterModel.Gemini_2_5_Flash, label: "Gemini 2.5 Flash (OR)" },
        { value: OpenRouterModel.GPT_4_1, label: "GPT-4.1 (OR)" },
        { value: OpenRouterModel.O3, label: "o3 (OR)" },
        { value: OpenRouterModel.O4_Mini, label: "o4-mini (OR)" },
      ],
    },
    {
      label: "Vercel AI Gateway",
      options: [
        { value: VercelModel.Claude_Opus_4_7, label: "Claude Opus 4.7 (Vercel)" },
        { value: VercelModel.Claude_Sonnet_4_6, label: "Claude Sonnet 4.6 (Vercel)" },
        { value: VercelModel.GPT_5_5, label: "GPT-5.5 (Vercel)" },
        { value: VercelModel.Gemini_3_5_Flash, label: "Gemini 3.5 Flash (Vercel)" },
        { value: VercelModel.Grok_4_3, label: "Grok 4.3 (Vercel)" },
      ],
    },
  ],
  [Agent.Cursor]: [
    {
      label: "Cursor",
      options: [
        { value: CursorModel.Composer_2_5, label: "Composer 2.5" },
        { value: CursorModel.Default, label: "Default" },
        { value: CursorModel.GPT_5_5, label: "GPT-5.5" },
        { value: CursorModel.GPT_5_4, label: "GPT-5.4" },
        { value: CursorModel.GPT_5_4_Mini, label: "GPT-5.4 Mini" },
        { value: CursorModel.GPT_5_3_Codex, label: "GPT-5.3 Codex" },
        { value: CursorModel.Claude_Opus_4_8, label: "Claude Opus 4.8" },
        { value: CursorModel.Claude_Opus_4_7, label: "Claude Opus 4.7" },
        { value: CursorModel.Claude_Sonnet_4_6, label: "Claude Sonnet 4.6" },
        { value: CursorModel.Claude_Sonnet_4_5, label: "Claude Sonnet 4.5" },
        { value: CursorModel.Gemini_3_1_Pro, label: "Gemini 3.1 Pro" },
        { value: CursorModel.Gemini_3_Flash, label: "Gemini 3 Flash" },
        { value: CursorModel.Grok_4_20, label: "Grok 4.20" },
        { value: CursorModel.Kimi_K2_5, label: "Kimi K2.5" },
      ],
    },
  ],
  [Agent.Custom]: [
    {
      label: "Custom",
      options: [{ value: "custom", label: "Custom" }],
    },
  ],
};
